// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/hlyyinif/Desktop/umi/umi-max/src/models/create';

export const models = {
model_1: { namespace: 'create', model: model_1 },
} as const
