// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/my","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"My","path":"/my","file":"@/pages/My/index.tsx","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"A","path":"/my/a","file":"@/pages/My/A/index.tsx","parentId":"2","id":"3"},"4":{"name":"B","path":"/my/a/b","file":"@/pages/My/A/B/index.tsx","parentId":"3","id":"4"},"5":{"name":"C","path":"/my/a/b/c","file":"@/pages/My/A/B/C/index.tsx","parentId":"4","id":"5"},"6":{"name":"D","path":"/my/a/b/c/d","file":"@/pages/My/A/B/C/D/index.tsx","parentId":"5","id":"6"},"7":{"name":"Element is my favososfdssfdsfsdgdg","path":"/my/a/b/c/d/e","file":"@/pages/My/A/B/C/D/E/index.tsx","parentId":"6","id":"7"},"8":{"name":"Friend","path":"/friend","file":"@/pages/Friend/index.tsx","parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"天气","path":"/weather","file":"@/pages/Weather/index.tsx","parentId":"ant-design-pro-layout","id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__My__index" */'@/pages/My/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__My__A__index" */'@/pages/My/A/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__My__A__B__index" */'@/pages/My/A/B/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__My__A__B__C__index" */'@/pages/My/A/B/C/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__My__A__B__C__D__index" */'@/pages/My/A/B/C/D/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__My__A__B__C__D__E__index" */'@/pages/My/A/B/C/D/E/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Friend__index" */'@/pages/Friend/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Weather__index" */'@/pages/Weather/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: ".umi__plugin-layout__Layout" */'@/.umi/plugin-layout/Layout.tsx')),
},
  };
}
